replicaCount: 1
image:
  repository: ui-service
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

config:
  applicationYml: |
    spring:
      application:
        name: ui-service
    resilience4j:
      retry:
        instances:
          accountsService:
            maxAttempts: 3
            waitDuration: 2s
            retryExceptions:
              - java.io.IOException
              - org.springframework.web.client.ResourceAccessException
              - org.springframework.web.client.HttpServerErrorException
          cashService:
            maxAttempts: 3
            waitDuration: 2s
            retryExceptions:
              - java.io.IOException
              - org.springframework.web.client.ResourceAccessException
              - org.springframework.web.client.HttpServerErrorException
          transferService:
            maxAttempts: 3
            waitDuration: 2s
            retryExceptions:
              - java.io.IOException
              - org.springframework.web.client.ResourceAccessException
              - org.springframework.web.client.HttpServerErrorException
      circuitbreaker:
        instances:
          accountsService:
            registerHealthIndicator: true
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
          cashService:
            registerHealthIndicator: true
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
          transferService:
            registerHealthIndicator: true
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
    jwt:
      validation:
        enabled: false
    management:
      endpoints:
        web:
          exposure:
            include: health, info
      endpoint:
        health:
          show-details: always

