apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exchange_generator_service.fullname" . }}-deployment
  labels:
    app: {{ include "exchange_generator_service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "exchange_generator_service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "exchange_generator_service.name" . }}
    spec:
      containers:
        - name: {{ include "exchange_generator_service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "file:/app/config/application.yml"
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "exchange_generator_service.fullname" . }}-config
            items:
              - key: application.yml
                path: application.yml
