replicaCount: 1
image:
  repository: transfer-service
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080


config:
  applicationYml: |
    spring:
      application:
        name: transfer-service
    resilience4j:
      retry:
        instances:
          exchangeService:
            maxAttempts: 3
            waitDuration: 2s
            retryExceptions:
              - java.io.IOException
              - org.springframework.web.client.ResourceAccessException
              - org.springframework.web.client.HttpServerErrorException
          accountsService:
            maxAttempts: 3
            waitDuration: 2s
            retryExceptions:
              - java.io.IOException
              - org.springframework.web.client.ResourceAccessException
              - org.springframework.web.client.HttpServerErrorException
          blockerService:
            maxAttempts: 3
            waitDuration: 2s
            retryExceptions:
              - java.io.IOException
              - org.springframework.web.client.ResourceAccessException
              - org.springframework.web.client.HttpServerErrorException
      circuitbreaker:
        instances:
          exchangeService:
            registerHealthIndicator: true
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
          accountsService:
            registerHealthIndicator: true
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
          blockerService:
            registerHealthIndicator: true
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
    jwt:
      validation:
        enabled: true
    management:
      endpoints:
        web:
          exposure:
            include: health, info
      endpoint:
        health:
          show-details: always

