apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-service
  template:
    metadata:
      labels:
        app: transfer-service
    spec:
      containers:
        - name: transfer-service
          image: transfer-service:1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: transfer-service
spec:
  type: ClusterIP
  selector:
    app: transfer-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080